weibo:
  client:
    clientId: 3050804627
    clientSecret: bf408e0747d07bd683599e6f539b61df
    accessTokenUri: https://api.weibo.com/oauth2/access_token
    userAuthorizationUri: https://api.weibo.com/oauth2/authorize
    clientAuthenticationScheme: form
    redirectUrl: http://127.0.0.1:8080/login/weibo
  resource:
    userInfoUri: https://api.weibo.com/user

logging:
  level:
    org.springframework.security: DEBUG